server:
  port: 9092
spring:
  application:
    name: service-emp-p
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro
    username: root
    password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
mybatis:
  type-aliases-package: com.qf.pojo
  mapper-locations: classpath*:mapping/*.xml

